// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/agency": {
    params: {};
  };
  "/agency/agents": {
    params: {};
  };
  "/agency/employees": {
    params: {};
  };
  "/agency/properties": {
    params: {};
  };
  "/agency/finance": {
    params: {};
  };
  "/agency/projects": {
    params: {};
  };
  "/agency/commercial": {
    params: {};
  };
  "/agency/validations": {
    params: {};
  };
  "/direction": {
    params: {};
  };
  "/hr": {
    params: {};
  };
  "/commercial": {
    params: {};
  };
  "/properties": {
    params: {};
  };
  "/visits": {
    params: {};
  };
  "/construction": {
    params: {};
  };
  "/finance": {
    params: {};
  };
  "/legal": {
    params: {};
  };
  "/documents": {
    params: {};
  };
  "/it": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/tickets": {
    params: {};
  };
  "/api/messages": {
    params: {};
  };
  "/debug/agency": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/agency" | "/agency/agents" | "/agency/employees" | "/agency/properties" | "/agency/finance" | "/agency/projects" | "/agency/commercial" | "/agency/validations" | "/direction" | "/hr" | "/commercial" | "/properties" | "/visits" | "/construction" | "/finance" | "/legal" | "/documents" | "/it" | "/login" | "/logout" | "/api/tickets" | "/api/messages" | "/debug/agency";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/" | "/agency" | "/agency/agents" | "/agency/employees" | "/agency/properties" | "/agency/finance" | "/agency/projects" | "/agency/commercial" | "/agency/validations" | "/direction" | "/hr" | "/commercial" | "/properties" | "/visits" | "/construction" | "/finance" | "/legal" | "/documents" | "/it";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/agency.tsx": {
    id: "routes/agency";
    page: "/agency" | "/agency/agents" | "/agency/employees" | "/agency/properties" | "/agency/finance" | "/agency/projects" | "/agency/commercial" | "/agency/validations";
  };
  "routes/agency.agents.tsx": {
    id: "routes/agency.agents";
    page: "/agency/agents";
  };
  "routes/agency.employees.tsx": {
    id: "routes/agency.employees";
    page: "/agency/employees";
  };
  "routes/agency.properties.tsx": {
    id: "routes/agency.properties";
    page: "/agency/properties";
  };
  "routes/agency.finance.tsx": {
    id: "routes/agency.finance";
    page: "/agency/finance";
  };
  "routes/agency.projects.tsx": {
    id: "routes/agency.projects";
    page: "/agency/projects";
  };
  "routes/agency.commercial.tsx": {
    id: "routes/agency.commercial";
    page: "/agency/commercial";
  };
  "routes/agency.validations.tsx": {
    id: "routes/agency.validations";
    page: "/agency/validations";
  };
  "routes/direction.tsx": {
    id: "routes/direction";
    page: "/direction";
  };
  "routes/hr.tsx": {
    id: "routes/hr";
    page: "/hr";
  };
  "routes/commercial.tsx": {
    id: "routes/commercial";
    page: "/commercial";
  };
  "routes/properties.tsx": {
    id: "routes/properties";
    page: "/properties";
  };
  "routes/visits.tsx": {
    id: "routes/visits";
    page: "/visits";
  };
  "routes/construction.tsx": {
    id: "routes/construction";
    page: "/construction";
  };
  "routes/finance.tsx": {
    id: "routes/finance";
    page: "/finance";
  };
  "routes/legal.tsx": {
    id: "routes/legal";
    page: "/legal";
  };
  "routes/documents.tsx": {
    id: "routes/documents";
    page: "/documents";
  };
  "routes/it.tsx": {
    id: "routes/it";
    page: "/it";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.tickets.tsx": {
    id: "routes/api.tickets";
    page: "/api/tickets";
  };
  "routes/api.messages.ts": {
    id: "routes/api.messages";
    page: "/api/messages";
  };
  "routes/debug.agency.tsx": {
    id: "routes/debug.agency";
    page: "/debug/agency";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/agency": typeof import("./app/routes/agency.tsx");
  "routes/agency.agents": typeof import("./app/routes/agency.agents.tsx");
  "routes/agency.employees": typeof import("./app/routes/agency.employees.tsx");
  "routes/agency.properties": typeof import("./app/routes/agency.properties.tsx");
  "routes/agency.finance": typeof import("./app/routes/agency.finance.tsx");
  "routes/agency.projects": typeof import("./app/routes/agency.projects.tsx");
  "routes/agency.commercial": typeof import("./app/routes/agency.commercial.tsx");
  "routes/agency.validations": typeof import("./app/routes/agency.validations.tsx");
  "routes/direction": typeof import("./app/routes/direction.tsx");
  "routes/hr": typeof import("./app/routes/hr.tsx");
  "routes/commercial": typeof import("./app/routes/commercial.tsx");
  "routes/properties": typeof import("./app/routes/properties.tsx");
  "routes/visits": typeof import("./app/routes/visits.tsx");
  "routes/construction": typeof import("./app/routes/construction.tsx");
  "routes/finance": typeof import("./app/routes/finance.tsx");
  "routes/legal": typeof import("./app/routes/legal.tsx");
  "routes/documents": typeof import("./app/routes/documents.tsx");
  "routes/it": typeof import("./app/routes/it.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/api.tickets": typeof import("./app/routes/api.tickets.tsx");
  "routes/api.messages": typeof import("./app/routes/api.messages.ts");
  "routes/debug.agency": typeof import("./app/routes/debug.agency.tsx");
};